title:              Jackdaw's Blog 
email:              blacknwhite8954@gmail.com
description:        기계공학 전공 개발자의 고군분투기
author:             Jackdaw
baseurl:            "" # "/startbootstrap-clean-blog-jekyll"
url:                "https://blacknwhite5.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    blacknwhite5
facebook_username:  blacknwhite5
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
